version: "3.1"
services:
  ingress:
    image: nginx:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ingress/etc/:/etc/nginx/
    depends_on:
      - horizon
      - stream
  horizon:
    image: registry.evertrust.io/horizon:2.5.0
    volumes:
      - ./horizon/license:/var/horizon/license/
    environment:
      MONGODB_URI: mongodb://mongo:27017/horizon
      APPLICATION_SECRET: evertrust
      EVENT_SEAL_SECRET: evertrust
      VAULT_TYPE: ssv
      VAULT_MASTER_PASSWORD: evertrust
      ACME_URL_SCHEME: http
      HOSTS_ALLOWED.0: .
      LICENSE_PATH: /var/horizon/license/horizon.lic
      HTTP_CERTIFICATE_HEADER: X-Forwarded-Tls-Client-Cert
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8558/ready" ]
      interval: 10s
      timeout: 60s
      retries: 7
  stream:
    image: registry.evertrust.io/stream:1.2.1
    platform: linux/amd64
    volumes:
      - ./stream/license:/var/stream/license/
      - ./stream/etc:/var/stream/etc/
    environment:
      MONGODB_URI: mongodb://mongo:27017/stream
      APPLICATION_SECRET: evertrust
      EVENT_SEAL_SECRET: itsnotevertrust
      VAULT_TYPE: ssv
      VAULT_MASTER_PASSWORD: evertrust
      ACME_URL_SCHEME: http
      HOSTS_ALLOWED.0: .
      LICENSE_PATH: /var/stream/license/stream.lic
      KEYSET_PATH: /var/stream/etc/keyset.json
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8558/ready" ]
      interval: 10s
      timeout: 60s
      retries: 7
  mongo:
    image: mongo:5
    restart: always
    command: --quiet
      #ports:
      # - "27017:27017"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/dump:/var/mongodb/dump:ro

  demo-client:
    profiles:
      - client
    build:
      context: ./demo-client
      args:
        REPOSITORY_USER: ${REPOSITORY_USER}
        REPOSITORY_PASSWORD: ${REPOSITORY_PASSWORD}
    env_file:
      - .env
    depends_on:
      - horizon
    privileged: true
    links:
      - ingress:horizon.lab
    ports:
      - "8443:443"
  demo-ansible:
    profiles:
      - ansible
    build:
      context: ./demo-ansible
    privileged: true
    depends_on:
      - horizon
